version: '3.7'

services:
  # jaeger-collector:
  #   image: jaegertracing/jaeger-collector:latest
  #   ports:
  #     - "14250:14250"
  #     - "14268:14268"
  #     - "14269:14269"
  #   environment:
  #     - SPAN_STORAGE_TYPE=memory

  # jaeger-query:
  #   image: jaegertracing/jaeger-query:latest
  #   ports:
  #     - "16686:16686"
  #   depends_on:
  #     - jaeger-collector

  # jaeger-agent:
  #   image: jaegertracing/jaeger-agent:latest
  #   ports:
  #     - "5775:5775/udp"
  #     - "6831:6831/udp"
  #     - "6832:6832/udp"
  #     - "5778:5778"
  #   environment:
  #     - COLLECTOR_HOST_PORT=jaeger-collector:14267
  #     - REPORTER_LOG_SPANS=true
  jaeger:
    image: jaegertracing/all-in-one:1.55
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "4317:4317"
      - "4318:4318"
      - "9411:9411"